### ISSUE TITLE
The incoming call screen does not appear when multiple apps are installed on Android

### ISSUE THREAD

**Issue by AAkira** [hiennguyen92/flutter_callkit_incoming#179]
The incoming call screen does not appear when multiple apps are installed on Android.

e.g.
* Development app and Production app are installed
* My developed and other developer's apps using this library are installed.

**Comment by yohanrw** [comment]
> 

I have the same issue. I have two apps, customer and supplier. `Callkit_incoming` is used in both apps. When both apps are installed in the same phone and when we get a call to a one app, the phone OS is asking whether we want to run this in customer app or supplier app. I have tested this in Android only, I believe the issue is same for iOS as well.

However this only happens if we if we click on the `callkit_incoming` notification and try to open the default ringing screen. If we accept or decline from the notification, this error do not happen.

**Comment by hiennguyen92** [comment]
Ok. Let me check. Thank you

**Comment by abel-wang-git** [comment]
I have the same issue.

**Comment by yohanrw** [comment]
> Ok

Appreciate it. I can confirm the issue is still there.

**Comment by abel-wang-git** [comment]
Because multiple apps have the same action
<img width="741" alt="image" src="https://user-images.githubusercontent.com/20026925/194968469-bfe88bce-2f67-4885-bff4-c55bd948c613.png">

This can be done temporarily
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/20026925/194968606-2c71e88e-c880-4bbe-b2fd-e7f54e377f8c.png">

CallkitIncomingBroadcastReceiver
<img width="953" alt="image" src="https://user-images.githubusercontent.com/20026925/194968884-536fbe96-1de8-4924-88be-415c607fadef.png">
CallkitIncomingActivity
<img width="991" alt="image" src="https://user-images.githubusercontent.com/20026925/194969004-76734628-2fb3-4df9-893d-a356c18f145e.png">

**Comment by 4tKnight** [comment]
Couldn't build because of issue getting appContext (CallkitIncomingActivity)

**Comment by HasanAlyazidi** [comment]
Same issue.

@hiennguyen92 Could you please check it out?

**Comment by hiennguyen92** [comment]
Ok. I will check and update soon.

**Comment by FutureSages** [comment]
Hi @hiennguyen92, i hope you are doing well, any updates?

**Comment by HasanAlyazidi** [comment]
Hi @hiennguyen92, i hope you are doing well, any updates?

**Comment by HasanAlyazidi** [comment]
@hiennguyen92 any updates?

**Comment by FutureSages** [comment]
Same issue in 3 apps.

**Comment by hiennguyen92** [comment]
please update version 1.0.3+1.

**Comment by HasanAlyazidi** [comment]
@hiennguyen92 thank you very much for your time and effort.
