### ISSUE TITLE
Android Call event not triggered when app is terminated

### ISSUE THREAD

**Issue by firgia** [hiennguyen92/flutter_callkit_incoming#212]
I have fatal issues when android is terminated.
1. When I accept the call, FlutterCallkitIncoming.onEvent is not triggered, and I can't get the active call when an app is opened.
2. When I declined the call, FlutterCallkitIncoming.onEvent is not triggered.

**Comment by erolyildiz33** [comment]
same problem . need help

**Comment by erolyildiz33** [comment]
@hiennguyen92 help please when app is terminated incoming call and trigered decline can not callback call information with FlutterCallkitIncoming.activeCalls() or which method how can i cache response decline?

**Comment by booooohdan** [comment]
@firgia @erolyildiz33
Try

@pragma('vm:entry-point')
Future _messagingBackgroundHandler(RemoteMessage message) async {
// your code here
}

**Comment by iYousafzai** [comment]
Any update on this? I am facing the same issue.

**Comment by MingSern** [comment]
Same issue here, it only happens to Android when terminated, 

> @firgia @erolyildiz33 Try
> 
> @pragma('vm:entry-point') Future _messagingBackgroundHandler(RemoteMessage message) async { // your code here }

As for the above solution, it seems that it doesn't work for me because I am using OneSignal, not Firebase.
Everything was working perfectly fine before, but now I'm not sure what happened and it's not working again. 

I am currently using:
```yaml
flutter: 3.7.8
flutter_callkit_incoming: ^1.0.3+3
onesignal_flutter: ^3.5.1
```
So the issue for me is that I use the `showIncomingNotification` function in native android (Kotlin) whenever a "call" notification is received as such:
```kotlin
// in my NotificationServiceExtension
val callkit = FlutterCallkitIncomingPlugin.getInstance()

callkit.showIncomingNotification(data)
```
It works when the app is in foreground/background, but when the app is terminated the call dialog is not shown. So I expected there's something to do with the `context` being null. So I "fix" it by manually creating the intent and passing the context as such:
```kotlin
// the context is from my NotificationServiceExtension
override fun remoteNotificationReceived(context: Context, notificationReceivedEvent: OSNotificationReceivedEvent) {
    ...
    val intent = CallkitIncomingBroadcastReceiver.getIntentIncoming(context, data.toBundle())

    CallkitNotificationManager(context).showIncomingNotification(data.toBundle())

    context.sendBroadcast(intent)

    notificationReceivedEvent.complete(null)
    ...
}
```
The above code will show the call dialog when the app is terminated, however when I tap on `Decline` or `Accept`, the `FlutterCallkitIncoming.onEvent.listen` is not working, it is not receiving any event.

Anyone can help? @hiennguyen92 

I can confirm this code worked previously, but I do not know what changed, Flutter's new version? Would be great to have an update about this.
